steps:
    - name: backend
      image: maven:3-eclipse-temurin-8
      commands:
          - mvn test
      failure: ignore
    - name: export result
      image: ghcr.io/crackito-io/crackito-junit-adapter:latest
      environment:
          FOLDER_PATH: target/surefire-reports
      secrets: [CALLBACK_TOKEN, WEBHOOK_URL]
